server: {port: 8083}
spring:
  datasource: {url: 'jdbc:mysql://127.0.0.1:3306/books?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai',
    username: root, password: test123456}
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: xyz.zinglizingli.books.po
  configuration: {log-impl: org.apache.ibatis.logging.stdout.StdOutImpl}
mysql: {charset: utf8mb4}
books: {lowestScore: 6.0}
crawl:
  website: {type: '4'}
  soft-novel: 0
  manhua: 0
logging: {config: 'classpath:logback-boot.xml'}
